/*
 * This file is part of the Flowee project
 * Copyright (C) 2023 Tom Zander <tom@flowee.org>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#include "ModuleManager.h"

#include <QFile>
#include <Logger.h>

#include <QCoreApplication>
#include <QLocale>
#include <QStandardPaths>
#include <QTranslator>
#include <stdexcept>

#include <boost/filesystem.hpp>

ModuleManager::ModuleManager(QObject *parent)
    : QObject(parent)
{
    m_configFile = QStandardPaths::locate(QStandardPaths::AppConfigLocation, "modules.conf");
    if (m_configFile.isEmpty()) {
        // make sure the directory exists
        auto path = QStandardPaths::writableLocation(QStandardPaths::AppConfigLocation);
        boost::filesystem::create_directories(boost::filesystem::path(path.toStdString()));
        m_configFile = path + '/' + "modules.conf";
    }
}

void ModuleManager::init()
{
    assert(m_modules.isEmpty()); // please don't call multiple times.
    extern void load_all_modules();
    // the load_all_modules method is generated by cmake in the modules builddir.
    load_all_modules();

    QFile config(m_configFile);
    if (config.open(QIODevice::ReadOnly)) {
        // TODO

    }
    // for now we just assume all are enabled ;-)
    for (auto *m : m_modules) {
        for (auto *s : m->sections()) {
            if (s->type() == ModuleSection::SendMethod) {
                m_sendMenuSections.append(s);
            }
        }
    }
}

void ModuleManager::registerModule(ModuleInfo *info)
{
    assert(info);
    if (info == nullptr)
        return;
    if (m_modules.contains(info))
        return;
    info->setParent(this);
    m_modules.append(info);

    auto translations = info->translationUnit();
    if (!translations.isEmpty()) {
        auto *translator = new QTranslator(this);
        /*
         * We try to load it from the default location as used in the translations subdir (:/i18n)
         * and if that fails we try again at the root level of the QRC because individual modules
         * can then just use one data.qrc and include translations, if they manage their own.
         */
        if (translator->load(QLocale(), translations, QLatin1String("_"), QLatin1String(":/i18n")))
            QCoreApplication::installTranslator(translator);
        else if (translator->load(QLocale(), translations, QLatin1String("_"), QLatin1String(":")))
            QCoreApplication::installTranslator(translator);
        else
            delete translator;
    }
}

QList<ModuleSection *> ModuleManager::sendMenuSections() const
{
    return m_sendMenuSections;
}

QList<ModuleInfo *> ModuleManager::registeredModules() const
{
    return m_modules;
}
