/*
 * This file is part of the Flowee project
 * Copyright (C) 2023 Tom Zander <tom@flowee.org>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#include "ModuleManager.h"

#include <QFile>
#include <Logger.h>

#include <QCoreApplication>
#include <QLocale>
#include <QStandardPaths>
#include <QTranslator>
#include <stdexcept>

#include <boost/filesystem.hpp>

ModuleManager::ModuleManager(QObject *parent)
    : QObject(parent)
{
    m_configFile = QStandardPaths::locate(QStandardPaths::AppConfigLocation, "modules.conf");
    if (m_configFile.isEmpty()) {
        // make sure the directory exists
        auto path = QStandardPaths::writableLocation(QStandardPaths::AppConfigLocation);
        boost::filesystem::create_directories(boost::filesystem::path(path.toStdString()));
        m_configFile = path + '/' + "modules.conf";
    }

    extern void load_all_modules(ModuleManager*);
    // the load_all_modules method is generated by cmake in the modules builddir.
    // it essentially makes each module call 'load' on this class.
    load_all_modules(this);

    QFile config(m_configFile);
    if (config.open(QIODevice::ReadOnly)) {
        // TODO

    }
    // for now we just assume all are enabled ;-)
    for (auto *m : m_modules) {
        for (auto *s : m->sections()) {
            if (s->type() == ModuleSection::SendMethod) {
                m_sendMenuSections.append(s);
            }
        }
    }
}

void ModuleManager::load(const char *translationUnit, const std::function<ModuleInfo *()> &function)
{
    if (translationUnit) {
        QString translations = QString::fromUtf8(translationUnit);
        auto *translator = new QTranslator(this);
        /*
         * We try to load it from the default location as used in the translations subdir (:/i18n)
         * and if that fails we try again at the root level of the QRC because individual modules
         * can then just use one data.qrc and include translations, if they manage their own.
         */
        if (translator->load(QLocale(), translations, QLatin1String("_"), QLatin1String(":/i18n")))
            QCoreApplication::installTranslator(translator);
        else if (translator->load(QLocale(), translations, QLatin1String("_"), QLatin1String(":")))
            QCoreApplication::installTranslator(translator);
        else
            delete translator;
    }
    auto *info = function();
    if (info == nullptr)
        return;
    info->setParent(this); // take ownership
    m_modules.append(info);
}

QList<ModuleSection *> ModuleManager::sendMenuSections() const
{
    return m_sendMenuSections;
}

QList<ModuleInfo *> ModuleManager::registeredModules() const
{
    return m_modules;
}
